import React from "react";
import { NextResponse } from "next/server";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { generateStaticDocumentDrafts } from "@/lib/ai/generate-documents";
import { getProposalProjectById } from "@/lib/data/proposal-projects";
import { renderPdfMarkdown } from "@/lib/markdown/pdf-render";

const s = StyleSheet.create({
  page: { padding: 48, fontFamily: "Helvetica", fontSize: 11, lineHeight: 1.6, color: "#1e1e1e" },
  coverPage: { justifyContent: "center", alignItems: "flex-start", backgroundColor: "#0f172a", padding: 64 },
  coverLabel: { fontSize: 10, color: "#f59e0b", textTransform: "uppercase", letterSpacing: 2.4, marginBottom: 12 },
  coverTitle: { fontSize: 28, color: "#f8fafc", fontWeight: "bold", lineHeight: 1.3, marginBottom: 16 },
  coverSub: { fontSize: 13, color: "#94a3b8", marginBottom: 4 },
  coverFooter: { fontSize: 10, color: "#64748b", marginTop: 48 },
  h1: { fontSize: 20, fontWeight: "bold", color: "#0f172a", marginTop: 28, marginBottom: 8, paddingBottom: 4, borderBottom: "2pt solid #f59e0b" },
  h2: { fontSize: 14, fontWeight: "bold", color: "#1e293b", marginTop: 18, marginBottom: 6 },
  body: { fontSize: 11, color: "#334155", marginBottom: 4, lineHeight: 1.6 },
  bullet: { fontSize: 11, color: "#334155", marginBottom: 2, marginLeft: 12, lineHeight: 1.6 },
  table: { marginTop: 8, marginBottom: 12 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e2e8f0", borderBottomStyle: "solid" },
  tableHeader: { flexDirection: "row", borderBottomWidth: 2, borderBottomColor: "#f59e0b", borderBottomStyle: "solid", marginBottom: 4 },
  thCell: { flex: 1, paddingVertical: 6, paddingRight: 8, fontSize: 10, fontWeight: "bold", color: "#0f172a" },
  tdCell: { flex: 1, paddingVertical: 5, paddingRight: 8, fontSize: 10, color: "#475569" },
  subdue: { fontSize: 9, color: "#94a3b8", marginTop: 8, lineHeight: 1.4 },
  sectionLabel: { fontSize: 10, color: "#f59e0b", textTransform: "uppercase", letterSpacing: 2.4, marginBottom: 16 },
  footer: { fontSize: 8, color: "#94a3b8", textAlign: "center", marginTop: 32 },
  bold: { fontWeight: "bold", color: "#0f172a" },
  plain: { color: "#334155" },
});

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = await getProposalProjectById(id);
  if (!project) return new NextResponse("Not found", { status: 404 });

  const drafts = generateStaticDocumentDrafts(project.structured_scope, undefined, project.client_name, project.project_type);
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const buffer = await renderToBuffer(
    React.createElement(Document, null,
      // COVER
      React.createElement(Page, { size: "A4", style: s.coverPage },
        React.createElement(Text, { style: s.coverLabel }, "ProposalCraft"),
        React.createElement(Text, { style: s.coverTitle }, `${project.project_type ?? "Project"} Proposal`),
        React.createElement(Text, { style: s.coverSub }, `Prepared for: ${project.client_name}`),
        React.createElement(Text, { style: s.coverSub }, `Date: ${today}`),
        React.createElement(Text, { style: s.coverFooter }, "Generated by ProposalCraft"),
      ),
      // PROPOSAL
      React.createElement(Page, { size: "A4", style: s.page },
        React.createElement(Text, { style: s.sectionLabel }, "Proposal"),
        ...renderPdfMarkdown(drafts.proposal.body, s, s.bold, s.plain),
        React.createElement(Text, { style: s.subdue }, `Page 1 — Proposal | ${project.client_name}`),
      ),
      // SOW
      React.createElement(Page, { size: "A4", style: s.page },
        React.createElement(Text, { style: s.sectionLabel }, "Statement of Work"),
        ...renderPdfMarkdown(drafts.sow.body, s, s.bold, s.plain),
        React.createElement(Text, { style: s.subdue }, `Page 2 — SOW | ${project.client_name}`),
      ),
      // QUOTE
      React.createElement(Page, { size: "A4", style: s.page },
        React.createElement(Text, { style: s.sectionLabel }, "Quote"),
        ...renderPdfMarkdown(drafts.quote.body, s, s.bold, s.plain),
        React.createElement(Text, { style: s.subdue }, `Page 3 — Quote | ${project.client_name}`),
      ),
    ),
  );

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="proposal-${project.client_name?.replace(/[^a-zA-Z0-9]/g, "-") ?? project.id}.pdf"`,
    },
  });
}
